## Setup a classification experiment

In [1]:
import pickle

In [2]:
import numpy as np

In [32]:
m1 = [+1 , -1]
edges1 =[10,50,100]

m2 = [+2, -2, +2 , +3]
edges2 =[0,33,66,90 , 120]
# new_edges= list(sorted(set([edges1 , edges2])))
# new_bin_edges =  list(sorted(set( [model.preprocessor_.bin_edges_[index] for model in models] ))) 
res = [2 ,1.5,-0.5,-1.5, 0.5, 1.0 , 3.0]
new_edg = sorted(set().union(*[set(edges1) , set(edges2)]))
new_edg
ne1 = np.searchsorted(edges1, new_edg)
ne2 = np.searchsorted(edges2, new_edg)

new_edg

[0, 10, 33, 50, 66, 90, 100, 120]

In [33]:
np.searchsorted(edges1, new_edg), np.searchsorted(edges2, new_edg)

(array([0, 0, 1, 1, 2, 2, 2, 3], dtype=int64),
 array([0, 1, 1, 2, 2, 3, 4, 4], dtype=int64))

In [37]:
models =[ m1 , m2]
ne = [ np.searchsorted(edges1, new_edg) , np.searchsorted(edges2, new_edg)]

In [56]:
r =[]
for idx, m in enumerate(models):
    # for i in range(1, len(new_edge)):
    print(ne[idx][1:])
    r.append([ m[x-1] if x > 0 and x <=len(m) else np.nan for x in ne[idx][1:] ])
r 

[0 1 1 2 2 2 3]
[1 1 2 2 3 4 4]


[[nan, 1, 1, -1, -1, -1, nan], [2, 2, -2, -2, 2, 3, 3]]

In [51]:
import scipy.stats.stats as st

In [57]:
a = [1,2,np.nan] 
np.nanmean(r, axis=0)


array([ 2. ,  1.5, -0.5, -1.5,  0.5,  1. ,  3. ])

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv(
    "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
    header=None)
df.columns = [
    "Age", "WorkClass", "fnlwgt", "Education", "EducationNum",
    "MaritalStatus", "Occupation", "Relationship", "Race", "Gender",
    "CapitalGain", "CapitalLoss", "HoursPerWeek", "NativeCountry", "Income"
]
# df = df.sample(frac=0.1, random_state=1)
train_cols = df.columns[0:-1]
label = df.columns[-1]
X = df[train_cols]
y = df[label].apply(lambda x: 0 if x == " <=50K" else 1) #Turning response into 0 and 1

seed = 1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=seed)

## Explore the dataset

In [6]:
from interpret import show
from interpret.data import ClassHistogram

hist = ClassHistogram().explain_data(X_train, y_train, name = 'Train Data')
# show(hist)

## Train the Explainable Boosting Machine (EBM)

In [4]:
from interpret.glassbox import ExplainableBoostingClassifier, LogisticRegression, ClassificationTree, DecisionListClassifier

ebm = ExplainableBoostingClassifier(random_state=seed, n_jobs=-1)
ebm.fit(X_train, y_train)   #Works on dataframes and numpy arrays

ExplainableBoostingClassifier(feature_names=['Age', 'WorkClass', 'fnlwgt',
                                             'Education', 'EducationNum',
                                             'MaritalStatus', 'Occupation',
                                             'Relationship', 'Race', 'Gender',
                                             'CapitalGain', 'CapitalLoss',
                                             'HoursPerWeek', 'NativeCountry',
                                             'Relationship x HoursPerWeek',
                                             'Age x Relationship',
                                             'MaritalStatus x HoursPerWeek',
                                             'EducationNum x Occupation',
                                             'fnlwgt x HoursPerWeek',
                                             'Occupat...
                              feature_types=['continuous', 'categorical',
                                             'co

In [28]:
seed =1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=seed)
ebm1 = ExplainableBoostingClassifier(random_state=seed, n_jobs=-1)
ebm1.fit(X_train, y_train)  

seed +=10
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=seed)
ebm2 = ExplainableBoostingClassifier(random_state=seed, n_jobs=-1)
ebm2.fit(X_train, y_train)  


seed +=10
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=seed)
ebm3 = ExplainableBoostingClassifier(random_state=seed, n_jobs=-1)
ebm3.fit(X_train, y_train)  



ExplainableBoostingClassifier(feature_names=['Age', 'WorkClass', 'fnlwgt',
                                             'Education', 'EducationNum',
                                             'MaritalStatus', 'Occupation',
                                             'Relationship', 'Race', 'Gender',
                                             'CapitalGain', 'CapitalLoss',
                                             'HoursPerWeek', 'NativeCountry',
                                             'Age x Relationship',
                                             'Relationship x HoursPerWeek',
                                             'Relationship x CapitalLoss',
                                             'WorkClass x Race',
                                             'Age x HoursPerWeek',
                                             'EducationNum x Occupati...
                              feature_types=['continuous', 'categorical',
                                             '

In [29]:
pickle.dump(ebm1,open("D:\\Projects\\interpret\\examples\\python\\notebooks\\ebm1.pickle", 'wb'))
pickle.dump(ebm2,open("D:\\Projects\\interpret\\examples\\python\\notebooks\\ebm2.pickle", 'wb'))
pickle.dump(ebm3,open("D:\\Projects\\interpret\\examples\\python\\notebooks\\ebm3.pickle", 'wb'))

In [30]:
ebm1 = pickle.load(open("D:\\Projects\\interpret\\examples\\python\\notebooks\\ebm1.pickle" ,'rb'))
ebm2 = pickle.load(open("D:\\Projects\\interpret\\examples\\python\\notebooks\\ebm2.pickle" ,'rb'))
ebm3 = pickle.load(open("D:\\Projects\\interpret\\examples\\python\\notebooks\\ebm3.pickle" ,'rb'))


In [70]:
ebm2.feature_names

['Age',
 'WorkClass',
 'fnlwgt',
 'Education',
 'EducationNum',
 'MaritalStatus',
 'Occupation',
 'Relationship',
 'Race',
 'Gender',
 'CapitalGain',
 'CapitalLoss',
 'HoursPerWeek',
 'NativeCountry',
 'Relationship x HoursPerWeek',
 'Age x Relationship',
 'MaritalStatus x HoursPerWeek',
 'EducationNum x MaritalStatus',
 'Age x CapitalLoss',
 'Age x HoursPerWeek',
 'Age x WorkClass',
 'WorkClass x Race',
 'Relationship x CapitalLoss',
 'Occupation x Relationship']

In [76]:
ebm1.preprocessor_.col_bin_counts_[0] , ebm2.preprocessor_.col_bin_counts_[0]

(array([  0, 317, 438, 568, 606, 575, 613, 697, 641, 669, 617, 672, 699,
        657, 684, 736, 659, 703, 696, 702, 719, 688, 663, 656, 643, 660,
        621, 604, 579, 574, 595, 561, 430, 460, 485, 485, 374, 373, 321,
        338, 289, 282, 297, 288, 254, 241, 199, 191, 170, 133, 111, 127,
         97,  84,  75,  55,  52,  51,  39,  37,  36,  25,  19,  37,  25,
         21,  35], dtype=int64),
 array([  0, 303, 445, 558, 607, 579, 618, 683, 644, 676, 606, 665, 705,
        639, 700, 704, 652, 714, 701, 708, 717, 677, 645, 640, 640, 630,
        631, 615, 583, 586, 599, 578, 434, 480, 492, 483, 384, 372, 340,
        333, 303, 286, 293, 294, 243, 235, 212, 183, 175, 144, 117, 117,
        102,  91,  72,  62,  48,  52,  31,  32,  35,  22,  20,  35,  23,
         18,  37], dtype=int64))

In [95]:
(ebm1.preprocessor_.col_bin_counts_[0])

array([  0, 317, 438, 568, 606, 575, 613, 697, 641, 669, 617, 672, 699,
       657, 684, 736, 659, 703, 696, 702, 719, 688, 663, 656, 643, 660,
       621, 604, 579, 574, 595, 561, 430, 460, 485, 485, 374, 373, 321,
       338, 289, 282, 297, 288, 254, 241, 199, 191, 170, 133, 111, 127,
        97,  84,  75,  55,  52,  51,  39,  37,  36,  25,  19,  37,  25,
        21,  35], dtype=int64)

In [133]:
for index,_ in enumerate(ebm1.feature_groups_):
    if index in ebm1.preprocessor_.col_bin_edges_.keys():
        print(index, len(ebm1.preprocessor_.col_bin_edges_[index]))

0 65
2 254
4 15
10 75
11 58
12 76


In [137]:
# ebm2.preprocessor_.col_bin_edges_[ebm1.feature_groups_[0]]
models=[ebm1, ebm2, ebm3]
ebm = ebm1
for index, _ in enumerate(ebm.feature_groups_):

    log_odds_tensors = []

    # Normalzing the bin edges for different models for each feature group
    if index in ebm.preprocessor_.col_bin_edges_.keys():

        print('---------', index) #, len(ebm1.preprocessor_.col_bin_edges_[index]))
        new_bin_edges = ebm.preprocessor_.col_bin_edges_[index]

        # list(ebm1.preprocessor_.col_bin_edges_.keys())[0]
        for model in models:
            print(len(model.preprocessor_.col_bin_edges_[index]))
            new_bin_edges = set(new_bin_edges).union(set(model.preprocessor_.col_bin_edges_[index]))

        print(' -->' ,len(new_bin_edges))

--------- 0
65
65
64
 --> 65
--------- 2
254
254
254
 --> 751
--------- 4
15
15
15
 --> 15
--------- 10
75
77
76
 --> 85
--------- 11
58
57
59
 --> 74
--------- 12
76
75
73
 --> 77


In [138]:
from interpret.glassbox.ebm.utils import *

In [ ]:
EBMUtils.merge_models(models)

In [104]:
len(set(ebm2.preprocessor_.col_bin_edges_[2]).union(set((ebm1.preprocessor_.col_bin_edges_[2]))))

506

In [79]:
ebm1.preprocessor_.col_bin_edges_

{0: array([17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5, 27.5,
        28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5, 38.5,
        39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5, 49.5,
        50.5, 51.5, 52.5, 53.5, 54.5, 55.5, 56.5, 57.5, 58.5, 59.5, 60.5,
        61.5, 62.5, 63.5, 64.5, 65.5, 66.5, 67.5, 68.5, 69.5, 70.5, 71.5,
        72.5, 73.5, 74.5, 75.5, 76.5, 77.5, 78.5, 80.5, 82.5, 89. ]),
 2: array([ 23562.5,  25943.5,  27778. ,  29440.5,  30570. ,  31748.5,
         32866.5,  33794.5,  34573. ,  35662.5,  37050. ,  38311. ,
         39652.5,  41877.5,  43979.5,  46392.5,  48290.5,  50249.5,
         52141. ,  53717. ,  55392.5,  57277.5,  59539.5,  62040. ,
         65009. ,  67220. ,  69552. ,  71717. ,  73802.5,  76330.5,
         78258. ,  80456. ,  82429. ,  83752. ,  85598.5,  87531.5,
         89448. ,  91220. ,  93208.5,  95159. ,  96455.5,  97806. ,
         98767. ,  99477. , 100809. , 101745.5, 102606.5, 103465. ,
        10

## Global Explanations: What the model learned overall

In [5]:
ebm_global = ebm.explain_global(name='EBM')
show(ebm_global)

<!-- http://127.0.0.1:7001/2793533953672/ -->

## Local Explanations: How an individual prediction was made

In [ ]:
ebm_local = ebm.explain_local(X_test[:5], y_test[:5], name='EBM')
show(ebm_local)

## Evaluate EBM performance

In [ ]:
from interpret.perf import ROC

ebm_perf = ROC(ebm.predict_proba).explain_perf(X_test, y_test, name='EBM')
show(ebm_perf)

## Let's test out a few other Explainable Models

In [ ]:
from interpret.glassbox import LogisticRegression, ClassificationTree

# We have to transform categorical variables to use Logistic Regression and Decision Tree
X_enc = pd.get_dummies(X, prefix_sep='.')
feature_names = list(X_enc.columns)
X_train_enc, X_test_enc, y_train, y_test = train_test_split(X_enc, y, test_size=0.20, random_state=seed)

lr = LogisticRegression(random_state=seed, feature_names=feature_names, penalty='l1', solver='liblinear')
lr.fit(X_train_enc, y_train)

tree = ClassificationTree()
tree.fit(X_train_enc, y_train)

## Compare performance using the Dashboard

In [ ]:
lr_perf = ROC(lr.predict_proba).explain_perf(X_test_enc, y_test, name='Logistic Regression')
tree_perf = ROC(tree.predict_proba).explain_perf(X_test_enc, y_test, name='Classification Tree')

show(lr_perf)
show(tree_perf)
show(ebm_perf)

## Glassbox: All of our models have global and local explanations

In [ ]:
lr_global = lr.explain_global(name='Logistic Regression')
tree_global = tree.explain_global(name='Classification Tree')

show(lr_global)
show(tree_global)
show(ebm_global)

## Dashboard: look at everything at once

In [ ]:
# Do everything in one shot with the InterpretML Dashboard by passing a list into show

show([hist, lr_global, lr_perf, tree_global, tree_perf, ebm_global, ebm_perf], share_tables=True)