In [1]:
import numpy as np

In [19]:
m1 = [0, +1 , -1 ]
edges1 =[1,50,100]

# m2 = [0,+2, -2, +2 , +3 , 9]
# edges2 =[20,33,66,90 , 120 ]

m2 = [0,+2, -2, +2 , +3 ]
edges2 =[20,33,66,90  ]

merged_edges = sorted(set().union(*[set(edges1) , set(edges2)]))
print(merged_edges)
# merged_bin_edges = sorted(set().union(*[ set(model.preprocessor_.col_bin_edges_[index]) for model in models]))


# ne1 = np.searchsorted(edges1, merged_edges)
# ne2 = np.searchsorted(edges2, merged_edges)

models =[ m1 , m2]
#  i if edges1[i-1] < merged_edges <= edges1[i]
ne = [ np.searchsorted( edges1,  merged_edges + [np.inf] ) , np.searchsorted(edges2,  merged_edges + [np.inf])]

# model_bin_edges = model.preprocessor_.col_bin_edges_[index]
# ne = np.searchsorted(model_bin_edges, merged_bin_edges + [np.inf])
ne

[1, 20, 33, 50, 66, 90, 100]


[array([0, 1, 1, 1, 2, 2, 2, 3], dtype=int64),
 array([0, 0, 1, 2, 2, 3, 4, 4], dtype=int64)]

In [20]:
r =[]
# and x <=len(mvalues)
for idx, m in enumerate(models):
    mvalues = m[1:]    
    r.append([ mvalues[x-1] if x > 0 and x <=len(mvalues) else np.nan for x in ne[idx][1:] ])

print(r)
meanr = np.nanmean(r, axis=0)
print("Merged Edges = " , merged_edges)
print("Merged Model= " , meanr)
# Merged Model=  [1.   1.5 -0.5 -1.5  0.5  1.   4.   7. ]

[[1, 1, 1, -1, -1, -1, nan], [nan, 2, -2, -2, 2, 3, 3]]
Merged Edges =  [1, 20, 33, 50, 66, 90, 100]
Merged Model=  [ 1.   1.5 -0.5 -1.5  0.5  1.   3. ]


In [35]:
col_map1={' ?': 1, 'Cambodia': 2, 'Canada': 3, 'Hungary': 4, 'India': 5}
model1 = [ 0, 2,3,4,5,6]

col_map2={' ?': 1, 'Cambodia': 2, 'Canada': 3, 'Haiti':4 ,'Hungary': 5, 'India': 6}
model2 = [ 0,10,20,30,40,50,60]

[ 6,23/2 ,34/2, 40 , 55/2 , 66/2]


[6, 11.5, 17.0, 40, 27.5, 33.0]

In [27]:
# merged_cols = sorted(set().union(*[set(col_map1.keys()) , set(col_map2.keys())]))
merged_cols = sorted(set().union( list(col_map1.keys()) + list(col_map2.keys()) ))
merged_cols


[' ?', 'Cambodia', 'Canada', 'Haiti', 'Hungary', 'India']

In [8]:
import numpy as np

In [28]:
models= [model1 , model2]
col_maps = [col_map1 , col_map2]

In [34]:
r =[]
for idx, col_map in enumerate(col_maps):
    mvalues = models[idx][1:]   
    mask = [ col_map.get(col, None ) for col in merged_cols]
    nmodel = [ models[idx][i] if i else np.nan for i in mask]

    r.append( nmodel)



# r.append( [ col_map1.get(col, np.nan) for col in merged_cols])
print(r)
rmean = np.nanmean(np.array(r), axis=0)
rmean

[[2, 3, 4, nan, 5, 6], [10, 20, 30, 40, 50, 60]]


array([ 6. , 11.5, 17. , 40. , 27.5, 33. ])

In [31]:
mask = [1, 2, 3, None, 4, 5]
nmodel= [ model1[i] if i else np.nan for i in mask]
nmodel

[2, 3, 4, nan, 5, 6]

In [42]:
a = np.array([1,2])
np.append(0., a)

array([0., 1., 2.])