In [1]:
import numpy as np

In [50]:
m1 = [5, 4, +1 , -1, 4 ]
bc1=[2,1,1,1,1]
edges1 =[1,50,100]

# m2 = [0,+2, -2, +2 , +3 , 9]
# edges2 =[20,33,66,90 , 120 ]

m2 = [6,4, +2, -2, +2 , +3, 7 ]
bc2=[1,2,2,2,2,2,2]
# edges2 =[1,33,50,66,100  ]
edges2 =[20,33,50,66,90  ]

merged_edges = sorted(set().union(*[set(edges1) , set(edges2)]))
print(merged_edges)

models =[ m1 , m2]
#  i if edges1[i-1] < merged_edges <= edges1[i]
bin_index = [ np.searchsorted( edges1,  merged_edges + [np.inf]  ) , np.searchsorted(edges2,  merged_edges + [np.inf])]

# model_bin_edges = model.preprocessor_.col_bin_edges_[index]
# ne = np.searchsorted(model_bin_edges, merged_bin_edges + [np.inf])
bin_index 

# [1, 20, 33, 50, 66, 90, 100]
# [array([0, 1, 1, 1, 2, 2, 2, 3], dtype=int64),
#  array([0, 0, 1, 2, 2, 3, 4, 4], dtype=int64)]

[1, 20, 33, 50, 66, 90, 100]


[array([0, 1, 1, 1, 2, 2, 2, 3], dtype=int64),
 array([0, 0, 1, 2, 3, 4, 5, 5], dtype=int64)]

In [53]:
r =[]
w=[]
wbc =[bc1, bc2]
# and x <=len(mvalues)
print("Merged Edges = " , merged_edges)
print('m1=', m1)
print('m2=' , m2)
for idx, m in enumerate(models):
    mvalues = m #[1:] 
    wvalues =wbc[idx]#[1:]   
    # r.append([ mvalues[x] if x >= 0 and x <len(mvalues) else np.nan for x in bin_index[idx] ])bin
    # bix = [0] + ( [ x+1 for x in bin_index[idx] ])
    bix = [0] + ( [ x+1 for x in bin_index[idx] ])
    print('bix=', bix)
    r.append([ mvalues[x] for x in bix ])
    w.append([ wvalues[x] for x in bix ])
    # new_model_ = [ mvalues[x-1] if x > 0 and x <=len(mvalues) else 0. for x in bin_indexs[1:] ]

print(r)
print(w)
meanr = np.average(r, axis=0 , weights=w)
# averaged_model = np.average(log_odds_tensors, axis=0 , weights=bin_weights )
#             m

print("Merged Model= " , meanr)
# Merged Model=  [1.   1.5 -0.5 -1.5  0.5  1.   4.   7. ]

# [[1, 1, 1, -1, -1, -1, nan], [nan, 2, -2, -2, 2, 3, 3]]
# Merged Edges =  [1, 20, 33, 50, 66, 90, 100]
# Merged Model=  [ 1.   1.5 -0.5 -1.5  0.5  1.   3. ]

Merged Edges =  [1, 20, 33, 50, 66, 90, 100]
m1= [5, 4, 1, -1, 4]
m2= [6, 4, 2, -2, 2, 3, 7]
bix= [0, 1, 2, 2, 2, 3, 3, 3, 4]
bix= [0, 1, 1, 2, 3, 4, 5, 6, 6]
[[5, 4, 1, 1, 1, -1, -1, -1, 4], [6, 4, 4, 2, -2, 2, 3, 7, 7]]
[[2, 1, 1, 1, 1, 1, 1, 1, 1], [1, 2, 2, 2, 2, 2, 2, 2, 2]]
Merged Model=  [ 5.33333333  4.          3.          1.66666667 -1.          1.
  1.66666667  4.33333333  6.        ]


In [35]:
col_map1={' ?': 1, 'Cambodia': 2, 'Canada': 3, 'Hungary': 4, 'India': 5}
model1 = [ 0, 2,3,4,5,6]

col_map2={' ?': 1, 'Cambodia': 2, 'Canada': 3, 'Haiti':4 ,'Hungary': 5, 'India': 6}
model2 = [ 0,10,20,30,40,50,60]

[ 6,23/2 ,34/2, 40 , 55/2 , 66/2]


[6, 11.5, 17.0, 40, 27.5, 33.0]

In [27]:
# merged_cols = sorted(set().union(*[set(col_map1.keys()) , set(col_map2.keys())]))
merged_cols = sorted(set().union( list(col_map1.keys()) + list(col_map2.keys()) ))
merged_cols


[' ?', 'Cambodia', 'Canada', 'Haiti', 'Hungary', 'India']

In [8]:
import numpy as np

In [28]:
models= [model1 , model2]
col_maps = [col_map1 , col_map2]

In [34]:
r =[]
for idx, col_map in enumerate(col_maps):
    mvalues = models[idx][1:]   
    mask = [ col_map.get(col, None ) for col in merged_cols]
    nmodel = [ models[idx][i] if i else np.nan for i in mask]

    r.append( nmodel)



# r.append( [ col_map1.get(col, np.nan) for col in merged_cols])
print(r)
rmean = np.nanmean(np.array(r), axis=0)
rmean

[[2, 3, 4, nan, 5, 6], [10, 20, 30, 40, 50, 60]]


array([ 6. , 11.5, 17. , 40. , 27.5, 33. ])

In [31]:
mask = [1, 2, 3, None, 4, 5]
nmodel= [ model1[i] if i else np.nan for i in mask]
nmodel

[2, 3, 4, nan, 5, 6]

In [42]:
a = np.array([1,2])
np.append(0., a)

array([0., 1., 2.])